USE mysql;

CREATE DATABASE pydao DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE USER 'pydao'@'%' IDENTIFIED BY 'pydao';
GRANT ALL PRIVILEGES ON pydao.* TO 'pydao'@'%';
FLUSH PRIVILEGES;

USE pydao;

CREATE TABLE produtos (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  preco DECIMAL(5,2) NOT NULL
);
