USE mysql;

CREATE DATABASE pydao DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON pydao.* TO 'pydao'@'%' IDENTIFIED BY 'pydao';
FLUSH PRIVILEGES;

CREATE TABLE produtos(
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  preco DECIMAL(5,2) NOT NULL
);
